# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/Eviden.VirtualGrocer/Client" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      aspnet:
        patterns:
          - "Microsoft.AspNetCore.*"
          - "Microsoft.Authentication.WebAssembly.Msal"
  - package-ecosystem: "nuget"
    directory: "/src/Eviden.VirtualGrocer/Server"
    schedule:
      interval: "daily"
    groups:
      aspnet:
        patterns:
          - "Microsoft.AspNetCore.*"
      identity:
        patterns:
          - "Microsoft.Identity.*"
